#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 30 13:15:36 2020

@author: altin
"""
from scipy.fftpack import fft2
import numpy as np
from skimage.filters import laplace
def M123(Data):
    M0 = np.sum(abs(fft2(Data)))
    M1 = np.sum(abs(fft2(Data))**2)
    M3 = np.sum(abs(laplace(Data))**2)
    return M0, M1, M3