#!/usr/bin/env python3
"""
"""
import pandas as pd
from reading import reading
from M123 import M123

def main():
    """
    """
    Data = reading('Bilder')
    M0arr = []
    M1arr = []
    M2arr = []
    M3arr = []
    Msarr = []
    for jj in range(9):
        M0, M1, M2, M3, Ms = M123(Data[jj])
        M0arr.append(M0)
        M1arr.append(M1)
        M2arr.append(M2)
        M3arr.append(M3)
        Msarr.append(Ms)
    M0 = M0arr/max(M0arr)
    M1 = M1arr/max(M1arr)
    M2 = M2arr/max(M2arr)
    M3 = M3arr/max(M3arr)
    Ms = Msarr/max(Msarr)

    df = pd.DataFrame(list(zip(M0, M1, M2, M3, Ms)), index =['Bild 0', 'Bild 1', 'Bild 2', 'Bild 3', 'Bild 4', 'Bild 5', 'Bild 6', 'Bild 7', 'Bild 8'], 
                                              columns =['M0', 'M1', 'M2', 'M3', 'Ms']) 
    print(df)


if __name__ == '__main__':
    main()
