#!/usr/bin/env python3
"""
"""

import matplotlib.pyplot as plt
import numpy as np
import argparse
from scipy import ndimage
from scipy.fftpack import fft2
from skimage.filters import laplace, gaussian
import os
import pickle
dir_path = os.path.dirname(os.path.realpath('__file__')) # in diesem Fall sollten die Bilder im gleichen Ordner wie die das Skript liegen
infile = open('Bilder', 'rb')
Data = pickle.load(infile)
infile.close()

def main():
    """
    """
    M0arr = []
    M1arr = []
    M2arr = []
    M3arr = []
    print(type(Data))
    for jj in range(9):
        M0, M1, M2, M3 = M123(Data[jj])
        M0arr.append(M0)
        M1arr.append(M1)
        M2arr.append(M2)
        M3arr.append(M3)
    M0 = M0arr/max(M0arr)
    M1 = M1arr/max(M1arr)
    M2 = M2arr/max(M2arr)
    M3 = M3arr/max(M3arr)
    print(M0)
    print(M1)
    print(M2)
    print(M3)


def M123(Data):
    M0 = np.sum(abs(fft2(Data)))
    M1 = np.sum(abs(fft2(Data))**2)
    M2 = np.sum(abs(ndimage.sobel(Data))**2)
    M3 = np.sum(abs(laplace(Data))**2)
    return M0, M1, M2, M3

if __name__ == '__main__':
    main()
