#!/usr/bin/env python3
"""
"""
from skimage.feature import canny
import matplotlib.pyplot as plt
from reading import reading as rd
def main():
    bild = 'Bilder'
    Data = rd(bild)
    bild= Data[1]
    bild_canny = canny(bild,3)
    #===============================#
    f = plt.figure()
    t1 = f.add_subplot(211)
    t1.axis('off')
    plt.imshow(bild)
    t2 = f.add_subplot(212)
    t2.axis('off')
    plt.imshow(bild_canny)
    f.set_figheight(15)
    f.set_figwidth(15)
    plt.show(block=True)

if __name__ == '__main__':
    main()

